In [0]:
from sklearn.cluster import KMeans
import numpy as np
kvalues=[2,3,4,5,6,2,2,3,3,4,4,5,5,6,6]
printList =["Kmeans clustering when k =2","Kmeans clustering when k =3","Kmeans clustering when k =4","Kmeans clustering when k =5","Kmeans clustering when k =6",
           "Kmeans clustering when k =2 and gamma=0.01","Kmeans clustering when k =2 and gamma=0.1","Kmeans clustering when k =3 and gamma=0.01","Kmeans clustering when k =3 and gamma=0.1"
            ,"Kmeans clustering when k =4 and gamma=0.01","Kmeans clustering when k =4 and gamma=0.1","Kmeans clustering when k =5 and gamma =0.01","Kmeans clustering when k =5 and gamma =0.1"
            ,"Kmeans clustering when k =6 and gamma =0.01","Kmeans clustering when k =6 and gamma =0.1"]


# a. Using Kmeans: set K=2,3,4,5,6. Report different clustering results.

In [0]:
#Question 1
data_array = [[2,4],[4,4],[3,4],[5,4],[5,6],[5,8],[6,4],[6,5],[6,7],[7,3],[7,4],[8,2],[9,4],[10,6],[10,7],[10,8],[11,5],[11,8],[12,7],[13,6],[13,7],[14,6],[15,5],[15,4]]
data_array = np.array(data_array);
kmeanLabels = []
for i in range(2,7):
 kmeans = KMeans(n_clusters=i, random_state=0).fit(data_array)
 kmeanLabels.append(kmeans.labels_)
#kmeanLabels = np.array(kmeanLabels)
print(np.array(kmeanLabels))


[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 0 0 0 0 0]
 [3 3 3 3 3 3 1 3 3 1 1 1 1 0 0 0 0 0 0 2 0 2 2 2]
 [4 4 4 4 3 3 1 1 3 1 1 1 1 0 0 0 0 0 0 2 2 2 2 2]
 [4 4 4 4 3 3 1 3 3 1 1 1 1 2 2 2 2 2 0 0 0 0 5 5]]


# b)i)Use RBF kernel with gamma = {0.01,0.1}. Report the Report
# different clustering results.

In [0]:
from sklearn.cluster import SpectralClustering
for i in range(2,7):
 #we calculate RBF -->np.exp(-gamma * d(X,X) ** 2)
 clustering1 = SpectralClustering(gamma=0.01,n_clusters=i,assign_labels="discretize",random_state=0).fit(data_array)
 clustering2 = SpectralClustering(gamma=0.1,n_clusters=i,assign_labels="discretize",random_state=0).fit(data_array)
 kmeanLabels.append(clustering1.labels_)
 kmeanLabels.append(clustering2.labels_)
print(np.array(kmeanLabels))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 0 0 0 0 0]
 [3 3 3 3 3 3 1 3 3 1 1 1 1 0 0 0 0 0 0 2 0 2 2 2]
 [4 4 4 4 3 3 1 1 3 1 1 1 1 0 0 0 0 0 0 2 2 2 2 2]
 [4 4 4 4 3 3 1 3 3 1 1 1 1 2 2 2 2 2 0 0 0 0 5 5]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 1 1 0 1 1 2 2 0 0 0 2 0 0 2 0 2 2 2]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 2 2 2 2 2]
 [3 3 3 3 3 0 1 3 0 1 1 1 1 0 0 0 1 0 0 2 2 2 2 2]
 [1 1 1 1 1 1 3 3 1 3 3 3 3 0 0 0 0 0 0 2 2 2 2 2]
 [4 4 4 4 1 1 3 1 1 3 3 3 3 0 0 0 3 0 0 2 2 2 2 2]
 [1 1 1 1 4 4 3 4 4 3 3 3 3 0 0 0 0 0 0 2 2 2 2 2]
 [2 2 2 2 3 3 2 3 3 2 2 2 1 5 0 0 1 0 0 4 4 4 4 4]
 [1 1 1 1 4 4 3 4 4 3 3 3 5 5 0 0 5 0 0 2 0 2 2 2]]


# ii. Use Similarity graph as the {3,5}-NN graph. Where Sim(xi,xj)=1
# iff xj is one of the nearest three points to xi (or vise versa ). Report
# different clustering results.

In [0]:
from sklearn.cluster import SpectralClustering
for i in range(2,7):
 clustering1 = SpectralClustering(affinity='nearest_neighbors',n_neighbors=3,n_clusters=i,assign_labels="discretize",random_state=0).fit(data_array)
 kmeanLabels.append(clustering1.labels_)
 clustering2 = SpectralClustering(affinity='nearest_neighbors',n_neighbors=5,n_clusters=i,assign_labels="discretize",random_state=0).fit(data_array)
 kmeanLabels.append(clustering2.labels_)
print(np.array(kmeanLabels))
kmeanLabels=np.array(kmeanLabels)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 0 0 0 0 0]
 [3 3 3 3 3 3 1 3 3 1 1 1 1 0 0 0 0 0 0 2 0 2 2 2]
 [4 4 4 4 3 3 1 1 3 1 1 1 1 0 0 0 0 0 0 2 2 2 2 2]
 [4 4 4 4 3 3 1 3 3 1 1 1 1 2 2 2 2 2 0 0 0 0 5 5]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 1 1 0 1 1 2 2 0 0 0 2 0 0 2 0 2 2 2]
 [1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 2 2 2 2 2]
 [3 3 3 3 3 0 1 3 0 1 1 1 1 0 0 0 1 0 0 2 2 2 2 2]
 [1 1 1 1 1 1 3 3 1 3 3 3 3 0 0 0 0 0 0 2 2 2 2 2]
 [4 4 4 4 1 1 3 1 1 3 3 3 3 0 0 0 3 0 0 2 2 2 2 2]
 [1 1 1 1 4 4 3 4 4 3 3 3 3 0 0 0 0 0 0 2 2 2 2 2]
 [2 2 2 2 3 3 2 3 3 2 2 2 1 5 0 0 1 0 0 4 4 4 4 4]
 [1 1 1 1 4 4 3 4 4 3 3 3 5 5 0 0 5 0 0 2 0 2 2 2]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 1 1 1 1 1]
 [3 3 3 3 2 2 2 2 2 2 2 2 0 0 0

# Needed Functions

# C)Compute the external measures we studied such as
## 1. Conditional Entropy

In [0]:
trueCluster=[0 ,0 ,0 ,1 ,1 ,1 ,1 ,1 ,1 ,1 ,1 ,1 ,1 ,2 ,2 ,2 ,2 ,2 ,2 ,2 ,2 ,2 ,2 ,2 ]
startof0 =0;
endof0 = 3;
startof1 =3;
endof1 = 13;
startof2 = 13;
endof2 = 24;
def Euclidean(a,b):
     return math.sqrt((a[0]-b[0])**2 +(a[1]-b[1])**2)
def mapClusterwithtrueOne(clusters,k):
  mp =np.zeros((3,k))
  for i in range(0,3):
    for j in range(0,k):
      mp[i][j]=0;
  for i in range(0,24):
    mp[trueCluster[i]][clusters[i]]=mp[trueCluster[i]][clusters[i]]+1;
  return mp
def totalSum(arr,k):
  sum=0;
  for i in range(0,k):
    sum+=arr[i];
  return sum

In [0]:
import math
def compute_Entropy(clusters,k):
    mymap = mapClusterwithtrueOne(clusters,k)
    for i in range(0,3):
      print("Entropy for cluster  ",i+1)
      sum = totalSum(mymap[i],k)
      entropy =0;
      for j in range(0,k):
        if(mymap[i][j] ==0):
           entropy -=(mymap[i][j]/sum)
        else: 
           entropy -=(mymap[i][j]/sum)*math.log(mymap[i][j]/sum,2)
      entropy = entropy * (sum/24)
      print("=",entropy)    


# 2. Purity


In [0]:
def compute_Purity(clusters,k):
    mymap = mapClusterwithtrueOne(clusters,k)
    totalpurity=0
    for i in range(0,3):
      purity=0
      sum = totalSum(mymap[i],k)
      purity = np.amax(mymap[i])/sum
      totalpurity += (sum/24)*purity
    print("Purity =",totalpurity)    

# 3. Pairwise measures (Jaccard and Rand index)


In [0]:
def Pairwise(clusters,k):
  TP=0;
  FP = 0
  FN = 0
  TN = 0
  for i  in range(0,24):
    for j in range(i+1,24):
      if clusters[i] == clusters[j]:
        if trueCluster[i] ==  trueCluster[j]:
          TP +=1
        else:
          FP +=1
      else:
        if trueCluster[i] ==  trueCluster[j]:
          FN +=1
        else:
          TN +=1
  rand = (TP + TN)/(TP + TN +FP + FN)
  jaccard = (TP)/(FN + TP + FP)
  print("Rand = ",rand)
  print("Jaccard = ",jaccard)
  
      

# 4. MaxMatching

In [0]:
def MaxMatching(clusters):
  mymap = mapClusterwithtrueOne(clusters,3)
  mx = 0
  mx = max(mymap[0][0]+mymap[1,1]+mymap[2,2],mymap[0][0]+mymap[1,2]+mymap[2,1],
                  mymap[0][1]+mymap[1,0]+mymap[2,2],mymap[0][1]+mymap[1,2]+mymap[2,0],
                  mymap[0][2]+mymap[1,1]+mymap[2,0],mymap[0][2]+mymap[1,0]+mymap[2,1])
  print("MaxMatching = ",mx/24)

# 5. FMeasure

In [0]:
def compute_FMeasure(clusters,k):
  mymap = mapClusterwithtrueOne(clusters,k)
  F = 0
  for i in range(0,3):
    sum = totalSum(mymap[i],k)
    prec =np.amax(mymap[i])/sum
    indx = np.argmax(mymap[i])
    recall = np.amax(mymap[i])/totalSum(mymap[:,indx],3)
    F += (2*prec*recall)/(prec+recall)
  print("FMeasure= ",F/k)

# Internal Measure

# BetaCV

In [0]:

#compact ---> between cluster and itself
def win(labels):
    w = 0
    for i in range(0,24):
       for j in range(0,24):
         if labels[i] == labels[j] :
           w += Euclidean(data_array[i],data_array[j])
    return w/2
 #between cluster and others
def wout(labels):
    w = 0
    for i in range(0,24):
       for j in range(0,24):
         if labels[i] != labels[j] :
           w += Euclidean(data_array[i],data_array[j])

    return w/2
def betaCV(labels,k):
    ni = np.zeros((k,1))
# cluster sizes
    for i in range(0,24):
       ni[labels[i]] += 1
    Nin = 0
    for i in range(0,k):
       Nin += ni[i]*(ni[i]-1)
    Nin *= 0.5
    Nout = 0
    for i in range(0,k):
     for j in range(i+1,k):
       Nout += ni[i] * ni[j]
    print(Nout*win(labels) / (Nin*wout(labels)))

# Normalized cut

In [0]:
def Normalized_Cut(labels,k):
  nc = 0
  for i in range(0,k):
    w1 = 0
    w2 = 0
    for j in range(0,24):
      if labels[j] != i :
         continue
    for k in range(0,24):
       dis = Euclidean(data_array[j],data_array[k])
       if labels[k] == labels[j] :
             w1 += dis
       else:
           w2 += dis
  nc += 1/((w1/w2)+1)
  print("Normalized cut",nc)

# Calculation

In [0]:

for i in range(0,len(kmeanLabels)):
  print(printList[i])
  print(kmeanLabels[i])
  compute_Entropy(kmeanLabels[i],kvalues[i])
  compute_Purity(kmeanLabels[i],kvalues[i])
  Pairwise(kmeanLabels[i],kvalues[i])
  compute_FMeasure(kmeanLabels[i],kvalues[i])
  betaCV(kmeanLabels[i],kvalues[i])
  Normalized_Cut(kmeanLabels[i],kvalues[i])
  if kvalues[i]==3:
     MaxMatching(kmeanLabels[i])
  
  

Kmeans clustering when k =2
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
Entropy for cluster   1
= 0.0
Entropy for cluster   2
= 0.0
Entropy for cluster   3
= 0.0
Purity = 1.0
Rand =  0.8913043478260869
Jaccard =  0.7744360902255639
FMeasure=  1.1222826086956523
[0.4324087]
Normalized cut 0.7498748080414097
Kmeans clustering when k =3
[1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 0 0 0 0 0]
Entropy for cluster   1
= 0.0
Entropy for cluster   2
= 0.19541483066220053
Entropy for cluster   3
= 0.4555971802602717
Purity = 0.75
Rand =  0.7391304347826086
Jaccard =  0.47058823529411764
FMeasure=  0.6282828282828282
[0.42794904]
Normalized cut 0.9414521502010061
MaxMatching =  0.625
Kmeans clustering when k =4
[3 3 3 3 3 3 1 3 3 1 1 1 1 0 0 0 0 0 0 2 0 2 2 2]
Entropy for cluster   1
= 0.0
Entropy for cluster   2
= 0.4166666666666667
Entropy for cluster   3
= 0.43342763960862674
Purity = 0.625
Rand =  0.7536231884057971
Jaccard =  0.423728813559322
FMeasure=  0.4974747474747474
[0.37818537]
Norm

IndexError: ignored